# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

import os

Import('env', 'config')

# Create a link to the toolchain's linker script directory.
if os.path.exists('ldscripts'):
	os.remove('ldscripts')
os.symlink('%s/%s/%s/toolchain-lib/ldscripts' % (config['TOOLCHAIN_DIR'], config['TOOLCHAIN_TARGET'], config['TOOLCHAIN_TARGET']),
           'ldscripts')

# Build all the libraries.
SConscript(dirs=[
	'libsystem',
	'libm',
	'libstdc++',
	'libkiwi',
	'rtld',
], exports=['env'])
