#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('manager')

env = manager.create(libraries = ['kiwi'])

env.KiwiService('service_manager', [
    'client.cpp',
    'service_manager.cpp',
    'service.cpp',
])
