#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'manager')

# Set the library output directory.
manager.add_variable('_LIBOUTDIR', Dir('.'))

# All core libraries must be visited first, and libraries that depend on other
# libraries must come after their dependencies.

core_minimal_c_libs = [
    'crt',
    'kernel',
    'system',
    'compiler-rt',
]

SConscript(dirs = core_minimal_c_libs)

if config['SYS_MINIMAL_USERSPACE']:
    Return()

core_c_libs = [
    'm'
]

SConscript(dirs = core_c_libs)

core_cxx_libs = [
    'cxxrt',
    'cxx',
    'kiwi',
]

SConscript(dirs = core_cxx_libs)

other_libs = [
    'device',
]

SConscript(dirs = other_libs)
