#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'mod_env')
from util import feature_dirs

mod_env.Module('input', [
    'input.c',
])

SConscript(dirs = feature_dirs(config, [
    ('DEVICE_INPUT_I8042', 'i8042'),
]))
