# Kiwi build system
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('env', 'sources')

# Generate the system call functions.
env.Sysgen('kernel/syscalls.S', 'kernel/syscalls.def')

sources += [
	File('ctype/isalnum.c'),
	File('ctype/isalpha.c'),
	File('ctype/isascii.c'),
	File('ctype/isblank.c'),
	File('ctype/iscntrl.c'),
	File('ctype/isdigit.c'),
	File('ctype/isgraph.c'),
	File('ctype/islower.c'),
	File('ctype/isprint.c'),
	File('ctype/ispunct.c'),
	File('ctype/isspace.c'),
	File('ctype/isupper.c'),
	File('ctype/isxdigit.c'),
	File('ctype/toascii.c'),
	File('ctype/tolower.c'),
	File('ctype/toupper.c'),

	File('kernel/device.c'),
	File('kernel/syscalls.S'),
	File('kernel/vm.c'),

	File('stdio/do_printf.c'),
	File('stdio/fclose.c'),
	File('stdio/fflush.c'),
	File('stdio/fgetc.c'),
	File('stdio/fgets.c'),
	File('stdio/fopen.c'),
	File('stdio/fputc.c'),
	File('stdio/fputs.c'),
	File('stdio/fread.c'),
	File('stdio/fseek.c'),
	File('stdio/fstatus.c'),
	File('stdio/fwrite.c'),
	File('stdio/vfprintf.c'),
	File('stdio/vsnprintf.c'),

	File('stdlib/abort.c'),
	File('stdlib/abs.c'),
	File('stdlib/atoi.c'),
	File('stdlib/bsearch.c'),
	File('stdlib/environ.c'),
	File('stdlib/exit.c'),
	File('stdlib/malloc.c'),
	File('stdlib/qsort.c'),
	File('stdlib/rand.c'),
	File('stdlib/strtoul.c'),

	File('string/memchr.c'),
	File('string/memcmp.c'),
	File('string/memcpy.c'),
	File('string/memmove.c'),
	File('string/memset.c'),
	File('string/strcasecmp.c'),
	File('string/strcat.c'),
	File('string/strchr.c'),
	File('string/strcmp.c'),
	File('string/strcpy.c'),
	File('string/strcspn.c'),
	File('string/strdup.c'),
	File('string/strlen.c'),
	File('string/strpbrk.c'),
	File('string/strsep.c'),
	File('string/strstr.c'),
	File('string/strtok.c'),

	File('fatal.c'),
	File('init.c'),
	File('rtld.c'),
]
