# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('env', 'config')

# Work out the drivers to build.
dirs = [
	('DRIVER_INPUT_I8042', 'i8042'),
]

SConscript(dirs=[d for (c, d) in dirs if not c or config[c]], exports=['env'])

# Build the input device manager.
env.Module('input', ['input.c'])
