#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config')

if config['SYS_MINIMAL_USERSPACE']:
    Return()

dirs = [
    'posix_service',
    'service_manager',
    'terminal_service',
    'test',
]

SConscript(dirs = dirs)
