#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('env', 'manager')

env.Command(
    'mbr.bin.c',
    ['mbr.bin'],
    Action('$BIN2HEX $SOURCE mbr_bin > $TARGET', '$GENCOMSTR'))

env.Program('image_tool', [
    'image_tool.c',
    'mbr.bin.c',
])

manager.add_variable('IMAGE_TOOL', File('image_tool'))
