#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('manager', 'config')

env = manager.create(libraries = ['system'], flags = {
    'CPPPATH': [Dir('include')],
    'CCFLAGS': [
        '-Wno-missing-field-initializers', '-Wno-sometimes-uninitialized',
        '-Wno-unused-const-variable', '-Wno-unused-variable',
    ],
    'CXXFLAGS': [
        '-Wno-implicit-exception-spec-mismatch',
    ],

    # We must use -nodefaultlibs as by default the build system would try
    # to make us link to ourself.
    'LINKFLAGS': ['-nodefaultlibs'],
})

libunwind_objects = SConscript(dirs = ['unwind'], exports = ['env'])

env.KiwiLibrary('cxxrt',
    sources = libunwind_objects + [
        'src/dynamic_cast.cc',
        'src/exception.cc',
        'src/guard.cc',
        'src/stdexcept.cc',
        'src/typeinfo.cc',
        'src/memory.cc',
        'src/auxhelper.cc',
        'src/libelftc_dem_gnu3.c',
    ],
    include_paths = [
        Dir('include'),
    ],
)
