#
# Copyright (C) 2013 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('env', 'config')

libunwind_objects = SConscript(dirs = ['unwind'], exports = ['env'])

env.KiwiLibrary('cxxrt',
    sources = libunwind_objects + [
        'src/dynamic_cast.cc',
        'src/exception.cc',
        'src/guard.cc',
        'src/stdexcept.cc',
        'src/typeinfo.cc',
        'src/memory.cc',
        'src/auxhelper.cc',
        'src/libelftc_dem_gnu3.c',
    ],
    libraries = ['system'],
    include_paths = [
        Dir('include'),
    ],
    flags = {
        'CCFLAGS': env['CCFLAGS'] + [
            '-Wno-missing-field-initializers', '-Wno-sometimes-uninitialized'
        ],
        'LINKFLAGS': ['-nodefaultlibs'],
    },
)
