#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('manager', 'config')

env = manager.create(flags = {
    'CPPPATH': [
        Dir('include'),
    ],
})

sources = [
    'device.c',
    'input.c',
    'net.c',
]

env.KiwiLibrary('device',
    sources = sources,
    include_paths = [Dir('include')],
)
