#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'mod_env')
from util import feature_dirs

SConscript(dirs = feature_dirs(config, [
    ('DEVICE_TIMER_ARM', 'arm_timer'),
]))
