#
# Copyright (C) 2009-2010 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED AS IS AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('env')

sources = map(File, [
	'context.S',
	'descriptor.c',
	'elf.c',
	'entry.S',
	'kdbg.c',
	'page.c',
	'syscall.c',
	'thread.c',
])

# Set AMD64-specific compilation flags.
env['ASFLAGS'] += ['-m64']
env['CCFLAGS'] += ['-m64', '-mcmodel=kernel', '-mno-red-zone']
env['LINKFLAGS'] += ['-Wl,-m,elf_x86_64']

Return('sources')
