#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'mod_env')
from util import feature_dirs

# Note that net.c is compiled as part of the net module.

SConscript(dirs = feature_dirs(config, [
    ('DEVICE_NET_VIRTIO_NET', 'virtio_net'),
]))
