#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_sources')
from util import feature_sources

kern_sources += feature_sources(config, [
    ('DEVICE_CONSOLE_NS16550', 'ns16550.c'),
    ('DEVICE_CONSOLE_PL011', 'pl011.c'),
    'serial.c',
])
