# Copyright (C) 2010 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('config', 'env', 'envmgr')

# Add sysgen to the build environments.
envmgr.AddVariable('SYSGEN', env.Program('sysgen', [
	'AMD64Target.cc',
	'IA32Target.cc',
	'parser.y',
	'lexer.l',
	'main.cc',
]))
envmgr.AddVariable('SYSGENFLAGS', [])

# Add builders to generate system call code.
envmgr.AddTool('SyscallTable', env['SYSGEN'], Action(
	'$SYSGEN $SYSGENFLAGS -t $TABLE -o $TARGET %s $SOURCES' % (config['ARCH']),
	'$GENCOMSTR'
))
envmgr.AddTool('SyscallHeader', env['SYSGEN'], Action(
	'$SYSGEN $SYSGENFLAGS -n $GUARD -o $TARGET %s $SOURCES' % (config['ARCH']),
	'$GENCOMSTR'
))
envmgr.AddTool('Syscalls', env['SYSGEN'], Action(
	'$SYSGEN $SYSGENFLAGS -o $TARGET %s $SOURCES' % (config['ARCH']),
	'$GENCOMSTR'
))
