#!/usr/bin/env python
#
# Binary to C file convertor
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

import sys

def usage():
	print 'Usage: %s [ARGS...] <binary> <variable name>' % (sys.argv[0])
	print 'Possible arguments:'
	print '  --no-size        - Do not create a size variable.'
	print '  --section <name> - Section to place array in.'

def main(args):
	size = True
	section = None

	# Parse arguments.
	while len(args) != 0 and args[0][0:2] == '--':
		arg = args.pop(0)
		if arg == '--help':
			usage()
			return 0
		elif arg == '--no-size':
			size = False
		elif arg == '--section':
			if len(args) == 0:
				print 'Argument %s requires a value' % (arg)
				usage()
				return 1
			section = args.pop(0)
		else:
			print 'Unknown argument %s' % (arg)
			usage()
			return 1
	if len(args) != 2:
		usage()
		return 1

	# Read in the file data.
	f = open(args[0], 'r')
	data = f.read()
	f.close()

	# Write it out.
	print '/* This file is automatically generated. Changes will be overwritten. */'
	if section:
		print 'unsigned char %s[] __attribute__((section("%s"))) = {' % (args[1], section)
	else:
		print 'unsigned char %s[] = {' % (args[1])
	for i in range(0, len(data)):
		print '0x%x,' % (ord(data[i]))
	print '};'
	if size:
		print 'unsigned int %s_size = %d;' % (args[1], len(data))

if __name__ == '__main__':
	sys.exit(main(sys.argv[1:]))
