#!/bin/bash
#
# Copyright (C) 2009-2021 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

#
# Invokes clang based on the current Kconfig.
#

source_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." &> /dev/null && pwd)"
config_file="${source_dir}/.config"

if [ ! -f "${config_file}" ]; then
    echo "Configuration file does not exist"
    exit 1
fi

eval "$(grep CONFIG_TOOLCHAIN_DIR "${config_file}")"
eval "$(grep CONFIG_TOOLCHAIN_TARGET "${config_file}")"

compiler_path="${CONFIG_TOOLCHAIN_DIR}/${CONFIG_TOOLCHAIN_TARGET}/bin/${CONFIG_TOOLCHAIN_TARGET}-clang"

exec "${compiler_path}" "$@"
