#!/bin/bash
#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

#
# Invokes clang based on the current Kconfig.
#

source_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." &> /dev/null && pwd)"
config_file="${source_dir}/.config"

if [ ! -f "${config_file}" ]; then
    echo "Configuration file does not exist"
    exit 1
fi

eval "$(grep CONFIG_TOOLCHAIN_DIR "${config_file}")"
eval "$(grep CONFIG_TOOLCHAIN_TARGET "${config_file}")"

compiler_path="${CONFIG_TOOLCHAIN_DIR}/${CONFIG_TOOLCHAIN_TARGET}/bin/${CONFIG_TOOLCHAIN_TARGET}-clang"

exec "${compiler_path}" "$@"
