#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('env', 'manager', 'version')

# Set paths to build utilities.
manager.add_variable('GENERRLIST', File('../../utilities/generrlist.py'))
manager.add_variable('BIN2HEX', File('../../utilities/bin2hex.py'))

# Visit subdirectories.
SConscript(exports = ['env'], dirs = [
    'image_tool',
    'kconfig',
    'sysgen'
])

# Build KBoot utilities.
kboot_env = manager.create_host(
    flags = {
        'OUTDIR': Dir('boot'),
        'LIBDIR': '/tmp/kboot/lib',
        'VERSION': 'kiwi-%s' % (version['KIWI_VER_STRING']),
        'CPPDEFINES': {
            'KBOOT_LIBDIR': '\\"${LIBDIR}\\"',
            'KBOOT_LOADER_VERSION': '\\"${VERSION}\\"',
        },
        'CCFLAGS': ['-Wno-format'],
    }
)

SConscript(dirs = ['boot'], exports = {'env': kboot_env})

manager.add_variable('KBOOT_INSTALL', File('boot/kboot-install'))
manager.add_variable('KBOOT_MKISO', File('boot/kboot-mkiso'))
