#
# Copyright (C) 2009-2022 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('env', 'manager', 'version')

# Set paths to build utilities.
manager.AddVariable('GENERRLIST', File('../../utilities/generrlist.py'))
manager.AddVariable('BIN2HEX', File('../../utilities/bin2hex.py'))

# Visit subdirectories.
SConscript(exports = ['env'], dirs = [
    'image_tool',
    'kconfig',
    'sysgen'
])

# Build KBoot utilities.
kboot_env = manager.CreateHost(
    flags = {
        'OUTDIR': Dir('boot'),
        'LIBDIR': '/tmp/kboot/lib',
        'VERSION': 'kiwi-%s' % (version['KIWI_VER_STRING']),
        'CPPDEFINES': {
            'KBOOT_LIBDIR': '\\"${LIBDIR}\\"',
            'KBOOT_LOADER_VERSION': '\\"${VERSION}\\"',
        },
        'CCFLAGS': ['-Wno-format'],
    }
)

SConscript(dirs = ['boot'], exports = {'env': kboot_env})

manager.AddVariable('KBOOT_INSTALL', File('boot/kboot-install'))
manager.AddVariable('KBOOT_MKISO', File('boot/kboot-mkiso'))
