/*
 * Copyright (C) 2010 Alex Smith
 *
 * Kiwi is open source software, released under the terms of the Non-Profit
 * Open Software License 3.0. You should have received a copy of the
 * licensing information along with the source code distribution. If you
 * have not received a copy of the license, please refer to the Kiwi
 * project website.
 *
 * Please note that if you modify this file, the license requires you to
 * ADD your name to the list of contributors. This boilerplate is not the
 * license itself; please refer to the copy of the license you have received
 * for complete terms.
 */

/**
 * @file
 * @brief		Key translation table.
 */

#include <drivers/input.h>

/** Map an uppercase ASCII character to a control character. */
#define ASCII_CTRL(c)		((c) & 0x1F)

extern unsigned char key_table[];
extern unsigned char key_table_shift[];
extern unsigned char key_table_ctrl[];

/** Normal key table. */
unsigned char key_table[] = {
	[INPUT_KEY_LCTRL] = 0,
	[INPUT_KEY_LALT] = 0,
	[INPUT_KEY_LSUPER] = 0,
	[INPUT_KEY_LSHIFT] = 0,
	[INPUT_KEY_RCTRL] = 0,
	[INPUT_KEY_RALT] = 0,
	[INPUT_KEY_RSUPER] = 0,
	[INPUT_KEY_RSHIFT] = 0,
	[INPUT_KEY_CAPSLOCK] = 0,
	[INPUT_KEY_SCROLLLOCK] = 0,
	[INPUT_KEY_NUMLOCK] = 0,
	[INPUT_KEY_ESC] = ASCII_CTRL('['),
	[INPUT_KEY_F1] = 0,
	[INPUT_KEY_F2] = 0,
	[INPUT_KEY_F3] = 0,
	[INPUT_KEY_F4] = 0,
	[INPUT_KEY_F5] = 0,
	[INPUT_KEY_F6] = 0,
	[INPUT_KEY_F7] = 0,
	[INPUT_KEY_F8] = 0,
	[INPUT_KEY_F9] = 0,
	[INPUT_KEY_F10] = 0,
	[INPUT_KEY_F11] = 0,
	[INPUT_KEY_F12] = 0,
	[INPUT_KEY_PRSCRN] = 0,
	[INPUT_KEY_PAUSE] = 0,
	[INPUT_KEY_0] = '0',
	[INPUT_KEY_1] = '1',
	[INPUT_KEY_2] = '2',
	[INPUT_KEY_3] = '3',
	[INPUT_KEY_4] = '4',
	[INPUT_KEY_5] = '5',
	[INPUT_KEY_6] = '6',
	[INPUT_KEY_7] = '7',
	[INPUT_KEY_8] = '8',
	[INPUT_KEY_9] = '9',
	[INPUT_KEY_MINUS] = '-',
	[INPUT_KEY_EQUAL] = '=',
	[INPUT_KEY_BACKSPACE] = '\b',
	[INPUT_KEY_TAB] = '\t',
	[INPUT_KEY_Q] = 'q',
	[INPUT_KEY_W] = 'w',
	[INPUT_KEY_E] = 'e',
	[INPUT_KEY_R] = 'r',
	[INPUT_KEY_T] = 't',
	[INPUT_KEY_Y] = 'y',
	[INPUT_KEY_U] = 'u',
	[INPUT_KEY_I] = 'i',
	[INPUT_KEY_O] = 'o',
	[INPUT_KEY_P] = 'p',
	[INPUT_KEY_LBRACE] = '[',
	[INPUT_KEY_RBRACE] = ']',
	[INPUT_KEY_ENTER] = '\r',
	[INPUT_KEY_A] = 'a',
	[INPUT_KEY_S] = 's',
	[INPUT_KEY_D] = 'd',
	[INPUT_KEY_F] = 'f',
	[INPUT_KEY_G] = 'g',
	[INPUT_KEY_H] = 'h',
	[INPUT_KEY_J] = 'j',
	[INPUT_KEY_K] = 'k',
	[INPUT_KEY_L] = 'l',
	[INPUT_KEY_SEMICOLON] = ';',
	[INPUT_KEY_APOSTROPHE] = '\'',
	[INPUT_KEY_BACKSLASH] = '\\',
	[INPUT_KEY_GRAVE] = '`',
	[INPUT_KEY_Z] = 'z',
	[INPUT_KEY_X] = 'x',
	[INPUT_KEY_C] = 'c',
	[INPUT_KEY_V] = 'v',
	[INPUT_KEY_B] = 'b',
	[INPUT_KEY_N] = 'n',
	[INPUT_KEY_M] = 'm',
	[INPUT_KEY_COMMA] = ',',
	[INPUT_KEY_PERIOD] = '.',
	[INPUT_KEY_SLASH] = '/',
	[INPUT_KEY_SPACE] = ' ',
	[INPUT_KEY_LEFT] = 0,
	[INPUT_KEY_RIGHT] = 0,
	[INPUT_KEY_UP] = 0,
	[INPUT_KEY_DOWN] = 0,
	[INPUT_KEY_INSERT] = 0,
	[INPUT_KEY_DELETE] = 0x7F,
	[INPUT_KEY_HOME] = 0,
	[INPUT_KEY_END] = 0,
	[INPUT_KEY_PGUP] = 0,
	[INPUT_KEY_PGDOWN] = 0,
	[INPUT_KEY_KPSLASH] = '/',
	[INPUT_KEY_KPASTERISK] = '*',
	[INPUT_KEY_KPMINUS] = '-',
	[INPUT_KEY_KPPLUS] = '+',
	[INPUT_KEY_KPENTER] = '\r',
	[INPUT_KEY_KP7] = '7',
	[INPUT_KEY_KP8] = '8',
	[INPUT_KEY_KP9] = '9',
	[INPUT_KEY_KP4] = '4',
	[INPUT_KEY_KP5] = '5',
	[INPUT_KEY_KP6] = '6',
	[INPUT_KEY_KP1] = '7',
	[INPUT_KEY_KP2] = '8',
	[INPUT_KEY_KP3] = '9',
	[INPUT_KEY_KP0] = '0',
	[INPUT_KEY_KPPERIOD] = '.',
};

/** Key table with Shift enabled. */
unsigned char key_table_shift[] = {
	[INPUT_KEY_LCTRL] = 0,
	[INPUT_KEY_LALT] = 0,
	[INPUT_KEY_LSUPER] = 0,
	[INPUT_KEY_LSHIFT] = 0,
	[INPUT_KEY_RCTRL] = 0,
	[INPUT_KEY_RALT] = 0,
	[INPUT_KEY_RSUPER] = 0,
	[INPUT_KEY_RSHIFT] = 0,
	[INPUT_KEY_CAPSLOCK] = 0,
	[INPUT_KEY_SCROLLLOCK] = 0,
	[INPUT_KEY_NUMLOCK] = 0,
	[INPUT_KEY_ESC] = ASCII_CTRL('['),
	[INPUT_KEY_F1] = 0,
	[INPUT_KEY_F2] = 0,
	[INPUT_KEY_F3] = 0,
	[INPUT_KEY_F4] = 0,
	[INPUT_KEY_F5] = 0,
	[INPUT_KEY_F6] = 0,
	[INPUT_KEY_F7] = 0,
	[INPUT_KEY_F8] = 0,
	[INPUT_KEY_F9] = 0,
	[INPUT_KEY_F10] = 0,
	[INPUT_KEY_F11] = 0,
	[INPUT_KEY_F12] = 0,
	[INPUT_KEY_PRSCRN] = 0,
	[INPUT_KEY_PAUSE] = 0,
	[INPUT_KEY_0] = ')',
	[INPUT_KEY_1] = '!',
	[INPUT_KEY_2] = '@',
	[INPUT_KEY_3] = '#',
	[INPUT_KEY_4] = '$',
	[INPUT_KEY_5] = '%',
	[INPUT_KEY_6] = '^',
	[INPUT_KEY_7] = '&',
	[INPUT_KEY_8] = '*',
	[INPUT_KEY_9] = '(',
	[INPUT_KEY_MINUS] = '_',
	[INPUT_KEY_EQUAL] = '+',
	[INPUT_KEY_BACKSPACE] = '\b',
	[INPUT_KEY_TAB] = '\t',
	[INPUT_KEY_Q] = 'Q',
	[INPUT_KEY_W] = 'W',
	[INPUT_KEY_E] = 'E',
	[INPUT_KEY_R] = 'R',
	[INPUT_KEY_T] = 'T',
	[INPUT_KEY_Y] = 'Y',
	[INPUT_KEY_U] = 'U',
	[INPUT_KEY_I] = 'I',
	[INPUT_KEY_O] = 'O',
	[INPUT_KEY_P] = 'P',
	[INPUT_KEY_LBRACE] = '{',
	[INPUT_KEY_RBRACE] = '}',
	[INPUT_KEY_ENTER] = '\n',
	[INPUT_KEY_A] = 'A',
	[INPUT_KEY_S] = 'S',
	[INPUT_KEY_D] = 'D',
	[INPUT_KEY_F] = 'F',
	[INPUT_KEY_G] = 'G',
	[INPUT_KEY_H] = 'H',
	[INPUT_KEY_J] = 'J',
	[INPUT_KEY_K] = 'K',
	[INPUT_KEY_L] = 'L',
	[INPUT_KEY_SEMICOLON] = ':',
	[INPUT_KEY_APOSTROPHE] = '"',
	[INPUT_KEY_BACKSLASH] = '|',
	[INPUT_KEY_GRAVE] = '~',
	[INPUT_KEY_Z] = 'Z',
	[INPUT_KEY_X] = 'X',
	[INPUT_KEY_C] = 'C',
	[INPUT_KEY_V] = 'V',
	[INPUT_KEY_B] = 'B',
	[INPUT_KEY_N] = 'N',
	[INPUT_KEY_M] = 'M',
	[INPUT_KEY_COMMA] = '<',
	[INPUT_KEY_PERIOD] = '>',
	[INPUT_KEY_SLASH] = '?',
	[INPUT_KEY_SPACE] = ' ',
	[INPUT_KEY_LEFT] = 0,
	[INPUT_KEY_RIGHT] = 0,
	[INPUT_KEY_UP] = 0,
	[INPUT_KEY_DOWN] = 0,
	[INPUT_KEY_INSERT] = 0,
	[INPUT_KEY_DELETE] = 0,
	[INPUT_KEY_HOME] = 0,
	[INPUT_KEY_END] = 0,
	[INPUT_KEY_PGUP] = 0,
	[INPUT_KEY_PGDOWN] = 0,
	[INPUT_KEY_KPSLASH] = '/',
	[INPUT_KEY_KPASTERISK] = '*',
	[INPUT_KEY_KPMINUS] = '-',
	[INPUT_KEY_KPPLUS] = '+',
	[INPUT_KEY_KPENTER] = '\n',
	[INPUT_KEY_KP7] = 0,
	[INPUT_KEY_KP8] = 0,
	[INPUT_KEY_KP9] = 0,
	[INPUT_KEY_KP4] = 0,
	[INPUT_KEY_KP5] = 0,
	[INPUT_KEY_KP6] = 0,
	[INPUT_KEY_KP1] = 0,
	[INPUT_KEY_KP2] = 0,
	[INPUT_KEY_KP3] = 0,
	[INPUT_KEY_KP0] = 0,
	[INPUT_KEY_KPPERIOD] = 0,
};

/** Key table with Ctrl pressed.
 * @note		If an entry is 0, the entry from the normal/shift table
 *			is used instead. */
unsigned char key_table_ctrl[] = {
	[INPUT_KEY_LCTRL] = 0,
	[INPUT_KEY_LALT] = 0,
	[INPUT_KEY_LSUPER] = 0,
	[INPUT_KEY_LSHIFT] = 0,
	[INPUT_KEY_RCTRL] = 0,
	[INPUT_KEY_RALT] = 0,
	[INPUT_KEY_RSUPER] = 0,
	[INPUT_KEY_RSHIFT] = 0,
	[INPUT_KEY_CAPSLOCK] = 0,
	[INPUT_KEY_SCROLLLOCK] = 0,
	[INPUT_KEY_NUMLOCK] = 0,
	[INPUT_KEY_ESC] = 0,
	[INPUT_KEY_F1] = 0,
	[INPUT_KEY_F2] = 0,
	[INPUT_KEY_F3] = 0,
	[INPUT_KEY_F4] = 0,
	[INPUT_KEY_F5] = 0,
	[INPUT_KEY_F6] = 0,
	[INPUT_KEY_F7] = 0,
	[INPUT_KEY_F8] = 0,
	[INPUT_KEY_F9] = 0,
	[INPUT_KEY_F10] = 0,
	[INPUT_KEY_F11] = 0,
	[INPUT_KEY_F12] = 0,
	[INPUT_KEY_PRSCRN] = 0,
	[INPUT_KEY_PAUSE] = 0,
	[INPUT_KEY_0] = 0,
	[INPUT_KEY_1] = 0,
	[INPUT_KEY_2] = 0,
	[INPUT_KEY_3] = 0,
	[INPUT_KEY_4] = 0,
	[INPUT_KEY_5] = 0,
	[INPUT_KEY_6] = 0,
	[INPUT_KEY_7] = 0,
	[INPUT_KEY_8] = 0,
	[INPUT_KEY_9] = 0,
	[INPUT_KEY_MINUS] = 0,
	[INPUT_KEY_EQUAL] = 0,
	[INPUT_KEY_BACKSPACE] = 0,
	[INPUT_KEY_TAB] = 0,
	[INPUT_KEY_Q] = ASCII_CTRL('Q'),
	[INPUT_KEY_W] = ASCII_CTRL('W'),
	[INPUT_KEY_E] = ASCII_CTRL('E'),
	[INPUT_KEY_R] = ASCII_CTRL('R'),
	[INPUT_KEY_T] = ASCII_CTRL('T'),
	[INPUT_KEY_Y] = ASCII_CTRL('Y'),
	[INPUT_KEY_U] = ASCII_CTRL('U'),
	[INPUT_KEY_I] = ASCII_CTRL('I'),
	[INPUT_KEY_O] = ASCII_CTRL('O'),
	[INPUT_KEY_P] = ASCII_CTRL('P'),
	[INPUT_KEY_LBRACE] = ASCII_CTRL('['),
	[INPUT_KEY_RBRACE] = ASCII_CTRL(']'),
	[INPUT_KEY_ENTER] = 0,
	[INPUT_KEY_A] = ASCII_CTRL('A'),
	[INPUT_KEY_S] = ASCII_CTRL('S'),
	[INPUT_KEY_D] = ASCII_CTRL('D'),
	[INPUT_KEY_F] = ASCII_CTRL('F'),
	[INPUT_KEY_G] = ASCII_CTRL('G'),
	[INPUT_KEY_H] = ASCII_CTRL('H'),
	[INPUT_KEY_J] = ASCII_CTRL('J'),
	[INPUT_KEY_K] = ASCII_CTRL('K'),
	[INPUT_KEY_L] = ASCII_CTRL('L'),
	[INPUT_KEY_SEMICOLON] = 0,
	[INPUT_KEY_APOSTROPHE] = 0,
	[INPUT_KEY_BACKSLASH] = ASCII_CTRL('\\'),
	[INPUT_KEY_GRAVE] = 0,
	[INPUT_KEY_Z] = ASCII_CTRL('Z'),
	[INPUT_KEY_X] = ASCII_CTRL('X'),
	[INPUT_KEY_C] = ASCII_CTRL('C'),
	[INPUT_KEY_V] = ASCII_CTRL('V'),
	[INPUT_KEY_B] = ASCII_CTRL('B'),
	[INPUT_KEY_N] = ASCII_CTRL('N'),
	[INPUT_KEY_M] = ASCII_CTRL('M'),
	[INPUT_KEY_COMMA] = 0,
	[INPUT_KEY_PERIOD] = 0,
	[INPUT_KEY_SLASH] = 0,
	[INPUT_KEY_SPACE] = 0,
	[INPUT_KEY_LEFT] = 0,
	[INPUT_KEY_RIGHT] = 0,
	[INPUT_KEY_UP] = 0,
	[INPUT_KEY_DOWN] = 0,
	[INPUT_KEY_INSERT] = 0,
	[INPUT_KEY_DELETE] = 0,
	[INPUT_KEY_HOME] = 0,
	[INPUT_KEY_END] = 0,
	[INPUT_KEY_PGUP] = 0,
	[INPUT_KEY_PGDOWN] = 0,
	[INPUT_KEY_KPSLASH] = 0,
	[INPUT_KEY_KPASTERISK] = 0,
	[INPUT_KEY_KPMINUS] = 0,
	[INPUT_KEY_KPPLUS] = 0,
	[INPUT_KEY_KPENTER] = 0,
	[INPUT_KEY_KP7] = 0,
	[INPUT_KEY_KP8] = 0,
	[INPUT_KEY_KP9] = 0,
	[INPUT_KEY_KP4] = 0,
	[INPUT_KEY_KP5] = 0,
	[INPUT_KEY_KP6] = 0,
	[INPUT_KEY_KP1] = 0,
	[INPUT_KEY_KP2] = 0,
	[INPUT_KEY_KP3] = 0,
	[INPUT_KEY_KP0] = 0,
	[INPUT_KEY_KPPERIOD] = 0,
};
