#
# Copyright (C) 2009-2021 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('config', 'kern_env', 'kern_sources')
from util import FeatureSources

# The Device Tree bus manager is built in to the kernel, since on DT platforms,
# core kernel functionality (IRQs, timers, low-level platform setup) is
# dependent on it.

kern_env['CPPPATH'] += [Dir('fdt/include')]

kern_sources += FeatureSources(config, [
    'fdt/fdt_addresses.c',
    'fdt/fdt.c',
    'fdt/fdt_check.c',
    'fdt/fdt_empty_tree.c',
    'fdt/fdt_overlay.c',
    'fdt/fdt_ro.c',
    'fdt/fdt_rw.c',
    'fdt/fdt_strerror.c',
    'fdt/fdt_sw.c',
    'fdt/fdt_wip.c',

    'dt.c',
])
