#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_env', 'kern_sources', 'mod_env')
from util import feature_sources

for env in [kern_env, mod_env]:
    env['CPPPATH'] += [Dir('fdt/include')]

kern_sources += feature_sources(config, [
    'fdt/fdt_addresses.c',
    'fdt/fdt.c',
    'fdt/fdt_check.c',
    'fdt/fdt_empty_tree.c',
    'fdt/fdt_overlay.c',
    'fdt/fdt_ro.c',
    'fdt/fdt_rw.c',
    'fdt/fdt_strerror.c',
    'fdt/fdt_sw.c',
    'fdt/fdt_wip.c',

    'dt.c',
    'irq.c',
])
