#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_sources')
from util import feature_dirs, feature_sources

kern_sources += feature_sources(config, [
    'context.c',
    'file.c',
    'file_map.c',
    'fs.c',
    'memory_file.c',
    'pipe.c',
    'request.c',
    'socket.c',
    'user_file.c',
])

SConscript(dirs = feature_dirs(config, [
    'fs',
]))
