#
# Copyright (C) 2009-2010 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED AS IS AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('config', 'env')

sources = map(File, [
	'arch.c',
	'context.c',
	'cpu.c',
	'fpu.c',
	'intr.c',
	'kdbg.c',
	'lapic.c',
	'signal.c',
	'time.c',
])

# Prevent FPU code generation, warn on stack frames that are too large.
env['CCFLAGS'] += [
	'-mno-sse', '-mno-mmx', '-mno-sse2', '-mno-3dnow',
	'-Wframe-larger-than=512',
]

# For debug builds, do not omit frame pointers.
if config['DEBUG']:
	env['CCFLAGS'] += ['-fno-omit-frame-pointer']

# Set the linker script path.
env['LDSCRIPT'] = env.LDScript('link.ld', 'link-%s.ld.in' % (config['ARCH']))

# Pull in AMD64-/IA32-specific stuff.
sources += SConscript(dirs=[config['ARCH']], exports=['env'])

Return('sources')
