#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_sources')
from util import feature_sources

kern_sources += feature_sources(config, [
    'kmem.c',
    'malloc.c',
    'mmu.c',
    'page.c',
    'page_cache.c',
    'phys.c',
    'safe.c',
    'slab.c',
    'vm.c',
])
