#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('mod_env')

mod_env.Module('ata', [
    'ata.c',
    'channel.c',
    'device.c',
    'sff.c',
])
