# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('env', 'envmgr', 'config')

target = env['LIBOUTDIR'].File('libstdc++.so')
source = File('%s/%s/%s/toolchain-lib/libstdc++.a' % (config['TOOLCHAIN_DIR'],
                                                      config['TOOLCHAIN_TARGET'],
                                                      config['TOOLCHAIN_TARGET']))

# Build the shared library from the static library that GCC built.
env.Command(target, source,
            Action('$CC $SHLINKFLAGS -o $TARGET -Wl,--whole-archive $SOURCE -Wl,--no-whole-archive -lm',
                   '$SHLINKCOMSTR'))

# Depend on libm and libc.
Depends(target, env['LIBOUTDIR'].File('libm.so'))
Depends(target, env['LIBOUTDIR'].File('libc.so'))

# Add the library to the libraries array.
envmgr['dist']['LIBRARIES'].append(target)
