#
# Copyright (C) 2009 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('env', 'envmgr', 'config')

target = env['LIBOUTDIR'].File('libstdc++.so')
source = File('%s/%s/%s/toolchain-lib/libstdc++.a' % (config['TOOLCHAIN_DIR'],
                                                      config['TOOLCHAIN_TARGET'],
                                                      config['TOOLCHAIN_TARGET']))

# Build the shared library from the static library that GCC built.
env.Command(target, source,
            Action('$CC $SHLINKFLAGS -o $TARGET -Wl,--whole-archive $SOURCE -Wl,--no-whole-archive -lm',
                   '$SHLINKCOMSTR'))

# Depend on libm and libc.
Depends(target, env['LIBOUTDIR'].File('libm.so'))
Depends(target, env['LIBOUTDIR'].File('libc.so'))

# Add the library to the libraries array.
envmgr['dist']['LIBRARIES'].append(target)
