#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('manager', 'config')

env = manager.create(
    libraries = ['system', 'cxxrt', 'm'],
    flags = {
        'CPPPATH': [Dir('include'), Dir('src')],
        'CPPDEFINES': {
            'LIBCXXRT': None,
            '_LIBCPP_BUILDING_LIBRARY': None,
        },
        'CXXFLAGS': [],

        # We must use -nodefaultlibs as by default the build system would try
        # to make us link to ourself.
        'LINKFLAGS': ['-nodefaultlibs'],
    },
)

env.KiwiLibrary('c++',
    sources = [
        'src/algorithm.cpp',
        'src/any.cpp',
        'src/atomic.cpp',
        'src/barrier.cpp',
        'src/bind.cpp',
        'src/charconv.cpp',
        'src/chrono.cpp',
        'src/condition_variable.cpp',
        'src/condition_variable_destructor.cpp',
        'src/exception.cpp',
        'src/functional.cpp',
        'src/future.cpp',
        'src/hash.cpp',
        'src/legacy_pointer_safety.cpp',
        'src/memory.cpp',
        'src/mutex.cpp',
        'src/mutex_destructor.cpp',
        'src/new.cpp',
        'src/optional.cpp',
        'src/random_shuffle.cpp',
        'src/ryu/d2fixed.cpp',
        'src/ryu/d2s.cpp',
        'src/ryu/f2s.cpp',
        'src/shared_mutex.cpp',
        'src/stdexcept.cpp',
        'src/string.cpp',
        'src/system_error.cpp',
        'src/thread.cpp',
        'src/typeinfo.cpp',
        'src/utility.cpp',
        'src/valarray.cpp',
        'src/variant.cpp',
        'src/vector.cpp',

        # LIBCXX_ENABLE_LOCALIZATION
        'src/ios.cpp',
        'src/ios.instantiations.cpp',
        'src/iostream.cpp',
        'src/locale.cpp',
        'src/regex.cpp',
        'src/strstream.cpp',

        # LIBCXX_ENABLE_FILESYSTEM
        #'src/filesystem/operations.cpp',
        #'src/filesystem/directory_iterator.cpp',

        'stubs.c',
    ],
    include_paths = [
        (Dir('include'), 'c++/v1'),
    ],
)
