#
# Copyright (C) 2013 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('manager', 'config')

env = manager.Create(
    libraries = ['system', 'cxxrt', 'm'],
    flags = {
        'CPPPATH': [Dir('include')],
        'CPPDEFINES': {
            'LIBCXXRT': None,
            'cxx_EXPORTS': None,
        },
        'CXXFLAGS': ['-Wno-old-style-cast'],

        # We must use -nodefaultlibs as by default the build system would try
        # to make us link to ourself.
        'LINKFLAGS': ['-nodefaultlibs'],
    },
)

env.KiwiLibrary('c++',
    sources = [
        'src/algorithm.cpp',
        'src/bind.cpp',
        #'src/chrono.cpp',
        'src/condition_variable.cpp',
        'src/debug.cpp',
        'src/exception.cpp',
        'src/future.cpp',
        'src/hash.cpp',
        'src/ios.cpp',
        'src/iostream.cpp',
        'src/locale.cpp',
        'src/memory.cpp',
        'src/mutex.cpp',
        'src/new.cpp',
        'src/random.cpp',
        'src/regex.cpp',
        'src/stdexcept.cpp',
        'src/string.cpp',
        'src/strstream.cpp',
        'src/system_error.cpp',
        'src/thread.cpp',
        'src/typeinfo.cpp',
        'src/utility.cpp',
        'src/valarray.cpp',
        'stubs.c',
    ],
    include_paths = [
        (Dir('include'), 'c++/v1'),
    ],
)
