#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('manager', 'config')

env = manager.create(flags = {
    'CPPPATH': [
        Dir('include'),
    ],
})

sources = [
    'core/event_loop.cpp',
]

# TODO: Split this into separate libraries once we have more (e.g. kiwi-core).
env.KiwiLibrary('kiwi',
    sources = sources,
    include_paths = [Dir('include')],
)
