# Copyright (C) 2010 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('env')

# Build the core library.
env.SharedLibrary('kiwi', [
	'org.kiwi.ServiceManager.cc',
	'Error.cc',
	'EventLoop.cc',
	'Handle.cc',
	'IPCConnection.cc',
	'IPCPort.cc',
	'log.cc',
	'Object.cc',
	'Process.cc',
	'RPCClientConnection.cc',
	'RPCMessageBuffer.cc',
	'RPCServerConnection.cc',
], LIBS=['stdc++'])

# Generate the service manager interface code.
env.RPCClient('org.kiwi.ServiceManager.cc', '../../services/svcmgr/org.kiwi.ServiceManager.proto')

# Build the additional libraries.
SConscript(dirs=['service', 'ui'], exports=['env'])
