# Copyright (C) 2010 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('env')

# Generate service manager interface code for the IPC classes.
env.RPCClient('org.kiwi.ServiceManager.cc', '../../services/svcmgr/org.kiwi.ServiceManager.proto')

# Build the core library.
env.KiwiLibrary('kiwi',
	sources = [
		'org.kiwi.ServiceManager.cc',
		'Error.cc',
		'EventLoop.cc',
		'Handle.cc',
		'IPCConnection.cc',
		'IPCPort.cc',
		'Log.cc',
		'Object.cc',
		'Process.cc',
		'RPCClientConnection.cc',
		'RPCMessageBuffer.cc',
		'RPCServerConnection.cc',
		'Signal.cc',
		'Thread.cc',
		'Timer.cc',
	],
	libraries = ['kernel'],
	flags = {
		'CCFLAGS': env['CCFLAGS'] + ['-fvisibility=hidden'],
	},
)

# Build the additional libraries.
SConscript(dirs=['Graphics', 'Service'], exports=['env'])
