# Kiwi build system
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('config', 'envmgr')

# Build rule for kernel component of POSIX subsystem.
envmgr['module'].Module('posix', [
	'posix.c',
], CPPPATH=envmgr['module']['CPPPATH'] + [Dir('include')])

# Set up the POSIX userspace build environment.
env = envmgr.Create('posix')
env['CPPPATH'] = Dir('include')

# FIXME: Temporary.
env['LINKFLAGS'] = '-static -nostdlib'
env['CCFLAGS'] = '-nostdlib'
