# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

subdirs = ['fs', 'platform']

#############################
# Build environment set-up. #
#############################

Import('config', 'envmgr')

# Create the module environment.
env = envmgr.Clone('module', 'kernel', {
	'MODULES': [],
	'CCFLAGS': ['-fno-common'],
	'LINKFLAGS': ['-r'],
})

# Add a builder to create kernel modules. The emitter adds all modules to the
# distribution environment's module list.
def module_emitter(target, source, env):
	envmgr['dist']['MODULES'].append(target[0])
	return target, source
env['BUILDERS']['Module'] = Builder(
	action=Action('$LINKCOM && $STRIP --strip-debug $TARGET', '$LINKCOMSTR'),
	suffix='.km',
	src_suffix='$OBJSUFFIX',
	src_builder='Object',
	emitter=module_emitter
)

# Get all of the modules and include directories into the array.
SConscript(dirs=subdirs, exports=['env'])
