#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_sources')
from util import feature_sources

kern_sources += feature_sources(config, [
    'ipc.c',
    'process.c',
    'sched.c',
    'thread.c',
])
