#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_sources', 'mod_env')
from util import feature_sources

mod_env.Module('net', [
    # The network device class code is under device/ just for consistency but
    # lives within the net module.
    '../device/net/net.c',

    'arp.c',
    'ethernet.c',
    'family.c',
    'interface.c',
    'ip.c',
    'ipv4.c',
    'net.c',
    'packet.c',
    'port.c',
    'socket.c',
    'tcp.c',
    'udp.c',
])
