#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'mod_env')
from util import feature_dirs

mod_env.Module('virtio', [
    'virtio.c',
])

if config['DEVICE_BUS_VIRTIO_PCI']:
    mod_env.Module('virtio_pci', [
        'virtio_pci.c',
    ])
