#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

from util import feature_sources
Import('config', 'kern_env', 'kern_sources', 'mod_env')

kern_sources += feature_sources(config, [
    'arch.c',
    'cpu.c',
    'elf.c',
    'entry.S',
    'exception.c',
    'kdb.c',
    'mmu.c',
    'page.c',
    'setjmp.S',
    'smp.c',
    'switch.S',
    'thread.c',
    'time.c',
])

for env in [kern_env, mod_env]:
    # Prevent FPU code generation.
    env['CCFLAGS'] += ['-mgeneral-regs-only']

    # Warn on stack frames that are too large.
    env['CCFLAGS'] += ['-Wframe-larger-than=512']

    # Default page size may be larger which can result in a large output binary.
    env['LINKFLAGS'] += ['-Wl,-z,max-page-size=0x1000', '-Wl,-z,common-page-size=0x1000']

# Set the linker script path.
kern_env['LDSCRIPT'] = kern_env.LDScript('link.ld', 'link.ld.in')
