#
# Copyright (C) 2009-2023 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

from util import feature_sources
Import('config', 'kern_env', 'kern_sources', 'mod_env')

kern_sources += feature_sources(config, [
    'arch.c',
    'cpu.c',
    'elf.c',
    'entry.S',
    'exception.c',
    'kdb.c',
    'mmu.c',
    'page.c',
    'setjmp.S',
    'smp.c',
    'switch.S',
    'thread.c',
    'time.c',
])

for env in [kern_env, mod_env]:
    # Prevent FPU code generation.
    env['CCFLAGS'] += ['-mgeneral-regs-only']

    # Warn on stack frames that are too large.
    env['CCFLAGS'] += ['-Wframe-larger-than=512']

    # Default page size may be larger which can result in a large output binary.
    env['LINKFLAGS'] += ['-Wl,-z,max-page-size=0x1000', '-Wl,-z,common-page-size=0x1000']

# Set the linker script path.
kern_env['LDSCRIPT'] = kern_env.LDScript('link.ld', 'link.ld.in')
