# Kiwi build system
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('env', 'config')

env['INCDIRS']['bus/pci'] = Dir('generic/include')

# Get the list of source files.
sources = []
if config['ARCH'] == 'amd64' or config['ARCH'] == 'ia32':
	SConscript(dirs=['arch/x86'], exports=['env', 'sources'])
SConscript(dirs=['generic'], exports=['env', 'sources'])

env.Module('pci', sources)
