#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('manager')

env = manager.create(libraries = ['kiwi'])

env.KiwiService('posix_service', [
    'posix_service.cpp',
    'process_group.cpp',
    'process.cpp',
    'session.cpp',
])
