#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_env', 'kern_sources')
from util import feature_sources

kern_sources += feature_sources(config, [
    'console.c',
    'fb.c',
    'font.c',
    'logo.c',
])

# Generate the boot splash image files.
kern_env.Command(
    'logo.c',
    ['logo.ppm'],
    Action('$BIN2HEX $SOURCE logo_ppm > $TARGET', '$GENCOMSTR'))
