# Copyright (C) 2010 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('env')

sources = map(File, [
	'ap_boot.S',
	'arch.c',
	'cpu.c',
	'enter.S',
	'except.S',
	'idt.c',
	'loader.c',
])

# Set build flags.
env['CCFLAGS'] += ['-m32', '-mno-sse', '-mno-mmx', '-mno-sse2', '-mno-3dnow']
env['ASFLAGS'] += ['-m32']
env['LINKFLAGS'] += ['-m32']
env['LIBS'] = ['gcc']

Return('sources')
