#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('env', 'config')

sources = [
    'src/libunwind.cpp',
    'src/Unwind-EHABI.cpp',
    'src/Unwind-seh.cpp',
    'src/UnwindLevel1.c',
    'src/UnwindLevel1-gcc-ext.c',
    'src/Unwind-sjlj.c',
    'src/UnwindRegistersRestore.S',
    'src/UnwindRegistersSave.S',
]

flags = {
    'CPPPATH': [
        Dir('src'),
        Dir('include'),
    ] + env['CPPPATH'],
    'CPPDEFINES': {
        '_LIBUNWIND_IS_NATIVE_ONLY': None,
    },
    'CPPFLAGS': [
        '-Wno-unused-but-set-variable',
    ]
}

targets = [env.SharedObject(f, **flags) for f in sources]

Return('targets')
