#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config')
from util import feature_dirs

SConscript(dirs = feature_dirs(config, [
    ('DEVICE_BUS_DT',       'dt'),
    ('DEVICE_BUS_PCI',      'pci'),
    ('DEVICE_BUS_VIRTIO',   'virtio'),
]))
