#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_sources')
from util import feature_sources

kern_sources += feature_sources(config, [
    'ansi_parser.c',
    'avl_tree.c',
    'bitmap.c',
    'fixed_heap.c',
    'id_allocator.c',
    'notifier.c',
    'printf.c',
    'qsort.c',
    'radix_tree.c',
    'random.c',
    'string.c',
    'tar.c',
])
