# Kiwi build system
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('sources')

sources += [
	File('ctype/isalnum.c'),
	File('ctype/isalpha.c'),
	File('ctype/isascii.c'),
	File('ctype/isblank.c'),
	File('ctype/iscntrl.c'),
	File('ctype/isdigit.c'),
	File('ctype/isgraph.c'),
	File('ctype/islower.c'),
	File('ctype/isprint.c'),
	File('ctype/ispunct.c'),
	File('ctype/isspace.c'),
	File('ctype/isupper.c'),
	File('ctype/isxdigit.c'),
	File('ctype/toascii.c'),
	File('ctype/tolower.c'),
	File('ctype/toupper.c'),

	File('stdio/do_printf.c'),
	File('stdio/fputs.c'),
	File('stdio/vfprintf.c'),
	File('stdio/vsnprintf.c'),

	File('stdlib/malloc.c'),
	File('stdlib/strtoul.c'),

	File('string/memchr.c'),
	File('string/memcmp.c'),
	File('string/memcpy.c'),
	File('string/memmove.c'),
	File('string/memset.c'),
	File('string/strcasecmp.c'),
	File('string/strcat.c'),
	File('string/strchr.c'),
	File('string/strcmp.c'),
	File('string/strcpy.c'),
	File('string/strcspn.c'),
	#File('string/strdup.c'),
	File('string/strlen.c'),
	File('string/strpbrk.c'),
	File('string/strsep.c'),
	File('string/strstr.c'),
	File('string/strtok.c'),
]

sources += [
	File('init.c'),
]
