# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('env')

sources = map(File, [
	'boot.S',
	'context.S',
	'descriptor.c',
	'elf.c',
	'entry.S',
	'kdbg.c',
	'page.c',
	'syscall.c',
	'thread.c',
])

# Set IA32-specific compilation flags.
env['ASFLAGS'] += ['-m32']
env['CCFLAGS'] += ['-m32', '-fno-omit-frame-pointer', '-march=i686']
env['LINKFLAGS'] += ['-Wl,-b,elf32-i386', '-Wl,-m,elf_i386']

# Need to link with libgcc, and force some symbols to be linked in for modules.
env['LIBS'] += ['gcc']
env['LINKFLAGS'] += ['--undefined=__moddi3', '--undefined=__divdi3']

Return('sources')
