# Kiwi build system
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('env', 'sources')

# Build rule to create required CRT files.
env.Object('%s/crt1.o' % (str(env['LIBOUTDIR'])), ['crt1.S'])
env.Object('%s/crti.o' % (str(env['LIBOUTDIR'])), ['crti.S'])
env.Object('%s/crtn.o' % (str(env['LIBOUTDIR'])), ['crtn.S'])

sources += [
	File('setjmp.S'),
]
