# Kiwi build system
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

import os
import sys

Import('env', 'config')

env['OBJFILES'] += [
	env.Object('acpi.c'),
	env.Object('console.c'),
	env.Object('font_8x8.c'),
	env.Object('kdbg.c'),
	env.Object('multiboot.c'),
	env.Object('pic.c'),
	env.Object('pit.c'),
	env.Object('platform.c'),
]

if config['SMP']:
	env['OBJFILES'].append(env.Object('smp.c'))
