#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('mod_env')

mod_env.Module('ext2', [
    'block.c',
    'dir.c',
    'ext2.c',
    'inode.c',
])
