#
# Copyright (C) 2009-2021 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('manager', 'config')

zconf = File('include/zconf.h')

env = manager.Create(
    flags = {
        'CFLAGS': ['-include', '%s' % (zconf.path)],
        'CPPDEFINES': {'PIC': None},
    }
)

sources = [
    'src/adler32.c',
    'src/crc32.c',
    'src/deflate.c',
    'src/infback.c',
    'src/inffast.c',
    'src/inflate.c',
    'src/inftrees.c',
    'src/trees.c',
    'src/zutil.c',
    'src/compress.c',
    'src/uncompr.c',
    'src/gzclose.c',
    'src/gzlib.c',
    'src/gzread.c',
    'src/gzwrite.c',
]

objects = [env.SharedObject(f) for f in sources]
Depends(objects, zconf)

env.KiwiLibrary('z',
    include_paths = [Dir('include')],
    sources = objects,
)
