# Copyright (C) 2010 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

# Kernel type definitions.
type handle_t int32_t;
type process_id_t int32_t;
type thread_id_t int32_t;
type port_id_t int32_t;
type semaphore_id_t int32_t;
type shm_id_t int32_t;
type mount_id_t uint16_t;
type node_id_t uint64_t;
type useconds_t int64_t;
type offset_t uint64_t;
type rel_offset_t int64_t;
