#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('manager')

env = manager.create(libraries = ['kiwi'], flags = {
    'CPPPATH': [
        Dir('../../lib/system'),
    ],
})

env.KiwiService('terminal_service', [
    'terminal_service.cpp',
    'terminal.cpp',
])
