# Kiwi build system
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('env', 'sources')

# Set AMD64-specific compilation flags.
env['ASFLAGS'] += ['-m64']
env['CCFLAGS'] += ['-m64', '-mcmodel=kernel', '-mno-red-zone', '-fno-omit-frame-pointer']
env['LDFLAGS'] += ['-A', 'x86_64', '-m', 'elf_x86_64']

# Pull in x86 common code.
SConscript(dirs=['../common/x86'], exports=['env', 'sources'])

# Add source files.
sources += [
	File('arch.c'),
	File('boot.S'),
	File('context.c'),
	File('descriptor.c'),
	File('elf.c'),
	File('entry.S'),
	File('kdbg.c'),
	File('page.c'),
	File('switch.S'),
	File('thread.c'),
]
