#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_sources')
from util import feature_sources, feature_dirs

kern_sources += feature_sources(config, [
    'bus.c',
    'class.c',
    'device.c',
    'dma.c',
    'io.c',
    'irq.c',
])

SConscript(dirs = feature_dirs(config, [
    'bus',
    'console',
    'disk',
    'irq',
    'input',
    'net',
    'timer',
]))
