# Kiwi build system
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

import os
import sys

Import('env', 'config')

# Generate the version information file. Thanks to the use of MD5 file
# checksums, this won't automatically be rebuilt!
def gen_version_c(target, source, env):
	f = open(str(target[0]), 'w')
	f.write('int kiwi_ver_release = %d;\n' % (env['KIWI_VER_RELEASE']))
	f.write('int kiwi_ver_update = %d;\n' % (env['KIWI_VER_UPDATE']))
	f.write('int kiwi_ver_revision = %d;\n' % (env['KIWI_VER_REVISION']))
	f.write('const char *kiwi_ver_codename = "%s";\n' % (env['KIWI_VER_CODENAME']))
	f.write('const char *kiwi_ver_string = "%s";\n' % (env['KIWI_VER_STRING']))
	f.close()
AlwaysBuild(env.Command('version.c', [], env.Action(gen_version_c, None)))

env['OBJFILES'] += [
	env.Object('console/console.c'),
	env.Object('console/kprintf.c'),
]

env['OBJFILES'] += [
	env.Object('cpu/cpu.c'),
	env.Object('cpu/intr.c'),
	env.Object('cpu/ipi.c'),
	env.Object('cpu/irq.c'),
]

env['OBJFILES'] += [
	env.Object('lib/do_printf.c'),
	env.Object('lib/qsort.c'),
	env.Object('lib/sprintf.c'),
	env.Object('lib/string.c'),
]

env['OBJFILES'] += [
	env.Object('mm/aspace.c'),
	env.Object('mm/aspace_anon.c'),
	env.Object('mm/cache.c'),
	env.Object('mm/kheap.c'),
	env.Object('mm/malloc.c'),
	env.Object('mm/pmm.c'),
	env.Object('mm/slab.c'),
	env.Object('mm/tlb.c'),
	env.Object('mm/vmem.c'),
]

env['OBJFILES'] += [
	env.Object('proc/process.c'),
	env.Object('proc/sched.c'),
	env.Object('proc/thread.c'),
]

env['OBJFILES'] += [
	env.Object('sync/mutex.c'),
	env.Object('sync/semaphore.c'),
	env.Object('sync/spinlock.c'),
	env.Object('sync/waitq.c'),
]

env['OBJFILES'] += [
	env.Object('time/timer.c'),
]

env['OBJFILES'] += [
	env.Object('types/avltree.c'),
	env.Object('types/bitmap.c'),
	env.Object('types/hash.c'),
	env.Object('types/radix.c'),
]

env['OBJFILES'] += [
	env.Object('bootmod.c'),
	env.Object('fatal.c'),
	env.Object('kdbg.c'),
	env.Object('main.c'),
	env.Object('module.c'),
	env.Object('symbol.c'),
	env.Object('version.c'),
]
