# Kiwi build system
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

Import('env', 'sources')

# Generate the version information file. Thanks to the use of MD5 file
# checksums, this won't be rebuilt unless the version info changes!
def gen_version_c(target, source, env):
	f = open(str(target[0]), 'w')
	f.write('int kiwi_ver_release = %d;\n' % (env['KIWI_VER_RELEASE']))
	f.write('int kiwi_ver_update = %d;\n' % (env['KIWI_VER_UPDATE']))
	f.write('int kiwi_ver_revision = %d;\n' % (env['KIWI_VER_REVISION']))
	f.write('const char *kiwi_ver_codename = "%s";\n' % (env['KIWI_VER_CODENAME']))
	f.write('const char *kiwi_ver_string = "%s";\n' % (env['KIWI_VER_STRING']))
	f.close()
AlwaysBuild(env.Command('version.c', [], env.Action(gen_version_c, None)))

sources += [
	File('console/console.c'),
	File('console/font_8x8.c'),
	File('console/kprintf.c'),

	File('cpu/cpu.c'),
	File('cpu/fpu.c'),
	File('cpu/irq.c'),
	File('cpu/ipi.c'),

	File('io/context.c'),
	File('io/device.c'),
	File('io/ramfs.c'),
	File('io/vfs.c'),

	File('ipc/ipc.c'),
	File('ipc/pipe.c'),

	File('lib/do_printf.c'),
	File('lib/notifier.c'),
	File('lib/qsort.c'),
	File('lib/sprintf.c'),
	File('lib/string.c'),

	File('mm/kheap.c'),
	File('mm/malloc.c'),
	File('mm/page.c'),
	File('mm/safe.c'),
	File('mm/slab.c'),
	File('mm/tlb.c'),
	File('mm/vm/anon.c'),
	File('mm/vm/page.c'),
	File('mm/vm/vm.c'),
	File('mm/vmem.c'),

	File('proc/handle.c'),
	File('proc/process.c'),
	File('proc/sched.c'),
	File('proc/syscall.c'),
	File('proc/thread.c'),

	File('sync/condvar.c'),
	File('sync/mutex.c'),
	File('sync/rwlock.c'),
	File('sync/semaphore.c'),
	File('sync/spinlock.c'),
	File('sync/waitq.c'),

	File('time/timer.c'),

	File('types/avl.c'),
	File('types/bitmap.c'),
	File('types/hash.c'),
	File('types/radix.c'),

	File('args.c'),
	File('bootmod.c'),
	File('elf.c'),
	File('fatal.c'),
	File('init.c'),
	File('kdbg.c'),
	File('module.c'),
	File('symbol.c'),
	File('version.c'),
]
