#
# Copyright (C) 2010-2013 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('manager', 'config')

env = manager.Create(libraries = ['kernel'], flags = {
    'LINKFLAGS': ['-nodefaultlibs'],
    'CPPPATH': [
        Dir('.'),
        Dir('include'),
        Dir('arch/%s/include' % (config['ARCH'])),
    ],
})

sources = map(File, [
    'core/mutex.c',

    'dirent/alphasort.c',
    'dirent/closedir.c',
    'dirent/opendir.c',
    'dirent/readdir.c',
    'dirent/rewinddir.c',
    'dirent/scandir.c',

    'locale/localeconv.c',
    'locale/setlocale.c',

    'posix/access.c',
    #'posix/alarm.c',
    'posix/chdir.c',
    #'posix/chmod.c',
    #'posix/chown.c',
    'posix/close.c',
    'posix/dup.c',
    'posix/execlp.c',
    'posix/execve.c',
    'posix/execvp.c',
    'posix/fcntl.c',
    'posix/fork.c',
    'posix/getcwd.c',
    'posix/getopt.c',
    'posix/getpid.c',
    'posix/ioctl.c',
    'posix/isatty.c',
    'posix/lseek.c',
    'posix/mkdir.c',
    'posix/mknod.c',
    'posix/mman.c',
    'posix/open.c',
    'posix/pipe.c',
    #'posix/poll.c',
    'posix/pwd.c',
    'posix/read.c',
    'posix/readlink.c',
    'posix/rmdir.c',
    'posix/sleep.c',
    'posix/stat.c',
    'posix/symlink.c',
    'posix/sync.c',
    'posix/termios.c',
    'posix/ttyname.c',
    #'posix/uidgid.c',
    #'posix/umask.c',
    'posix/unlink.c',
    'posix/utime.c',
    'posix/wait.c',
    'posix/write.c',

    'pthread/cond.c',
    'pthread/mutex.c',
    'pthread/once.c',
    'pthread/pthread.c',
    'pthread/specific.c',

    'signal/kill.c',
    'signal/sigaction.c',
    'signal/sigaltstack.c',
    'signal/sigprocmask.c',
    'signal/sigset.c',
    'signal/sigsetjmp.c',
    'signal/sigsuspend.c',
    'signal/strsignal.c',

    'stdio/buffer.c',
    'stdio/do_printf.c',
    'stdio/do_scanf.c',
    'stdio/fclose.c',
    'stdio/fflush.c',
    'stdio/fgetc.c',
    'stdio/fgets.c',
    'stdio/fopen.c',
    'stdio/fputc.c',
    'stdio/fputs.c',
    'stdio/fread.c',
    'stdio/fseek.c',
    'stdio/fstatus.c',
    'stdio/fwrite.c',
    'stdio/perror.c',
    'stdio/remove.c',
    'stdio/rename.c',
    'stdio/tmpfile.c',
    'stdio/vfprintf.c',
    'stdio/vfscanf.c',
    'stdio/vsnprintf.c',
    'stdio/vsscanf.c',

    'stdlib/abort.c',
    'stdlib/abs.c',
    'stdlib/atoi.c',
    'stdlib/bsearch.c',
    'stdlib/environ.c',
    'stdlib/exit.c',
    'stdlib/ldiv.c',
    'stdlib/malloc.c',
    'stdlib/mkstemp.c',
    'stdlib/qsort.c',
    'stdlib/rand.c',
    'stdlib/strtod.c',
    'stdlib/strtoul.c',
    'stdlib/system.c',

    'string/ffs.c',
    'string/memchr.c',
    'string/memcmp.c',
    'string/memcpy.c',
    'string/memmove.c',
    'string/memset.c',
    'string/strcasecmp.c',
    'string/strcat.c',
    'string/strchr.c',
    'string/strcmp.c',
    'string/strcpy.c',
    'string/strcspn.c',
    'string/strdup.c',
    'string/strerror.c',
    'string/strlen.c',
    'string/strpbrk.c',
    'string/strsep.c',
    'string/strstr.c',
    'string/strtok.c',

    'time/asctime.c',
    'time/gettimeofday.c',
    'time/gmtime.c',
    'time/localtime.c',
    'time/mktime.c',
    'time/nanosleep.c',
    'time/strftime.c',
    'time/time.c',

    'ctype.c',
    'errno.c',
    'error_list.c',
    'fatal.c',
    'init.c',
    'sched.c',
])

# Generate the error string list.
env.Command(
    'error_list.c',
    ['include/errno.h'],
    Action('$GENERRLIST $SOURCE __errno_list __errno_count > $TARGET', '$GENCOMSTR')
)

# Get a list of architecture-specific source files.
arch_sources = SConscript(dirs = ['arch/' + config['ARCH']], exports = ['env'])

# Build the library from this.
env.KiwiLibrary('system',
    sources = arch_sources + sources,
    build_libraries = ['kernel'],
    include_paths = [
        Dir('include'),
        Dir('arch/%s/include' % (config['ARCH'])),
    ],
)
