#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_sources')
from util import feature_sources

kern_sources += feature_sources(config, [
    'condition.c',
    'condvar.c',
    'futex.c',
    'mutex.c',
    'rwlock.c',
    'semaphore.c',
    'spinlock.c',
])
