# Copyright (C) 2009-2010 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

sources = map(File, [
	'ap_boot.bin.c',
	'cpu.c',
	'fpu.c',
	'intr.c',
	'kdbg.c',
	'lapic.c',
	'smp.c',
	'vm.c',
])

Import('env')

# Set build flags to prevent FPU code generation.
env['CCFLAGS'] += ['-mno-sse', '-mno-mmx', '-mno-sse2', '-mno-3dnow']

# Generate the AP boot code.
Import('envmgr')
env.Object('ap_boot.S')
env.Command('ap_boot.bin.elf', ['ap_boot.o'], Action('%s -Ttext=0 -o $TARGET $SOURCE' % (envmgr.GetToolPath('ld')), None))
env.Command('ap_boot.bin', ['ap_boot.bin.elf'], Action('$OBJCOPY -O binary $SOURCE $TARGET', None))
env.Command('ap_boot.bin.c', ['ap_boot.bin'],
            Action('$BIN2HEX --no-size --section .init.trampoline $SOURCE __smp_trampoline > $TARGET',
                   '$GENCOMSTR'))

Return('sources')
