# Kiwi build system
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

import os
import sys

Import('env', 'config')

# Set build flags, prevent FPU code generation.
env['CCFLAGS'] += ['-mno-sse', '-mno-mmx', '-mno-sse2', '-mno-3dnow']

# Add source files.
env['OBJFILES'] += [
	env.Object('aspace.c'),
	env.Object('cpu.c'),
	env.Object('fault.c'),
	env.Object('kdbg.c'),
	env.Object('lapic.c'),
	env.Object('string.c'),
]

if config['SMP']:
	env['OBJFILES'].append(env.Object('smp.c'))
