#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

sources = [File(f) for f in [
    'relocate.c',
    'rtld.c',
    'start.S',
    'tls.c',
]]

Return('sources')
