#
# Copyright (C) 2009-2023 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('env', 'manager')

sysroot_env = manager['sysroot']

crt_files        = ['crt1', 'crti', 'crtn', 'crtbegin', 'crtend']
shared_crt_files = ['crtbegin', 'crtend']

for file in crt_files:
    path = '%s/%s.o' % (str(env['_LIBOUTDIR']), file)
    env.Object(path, ['%s.S' % (file)])
    sysroot_env.AddFile(File(path), 'lib/%s.o' % (file))

for file in shared_crt_files:
    path = '%s/%sS.o' % (str(env['_LIBOUTDIR']), file)
    env.Object(path, ['%s.S' % (file)], CPPDEFINES = {'PIC': None, 'SHARED': None })
    sysroot_env.AddFile(File(path), 'lib/%sS.o' % (file))
