#
# Copyright (C) 2009-2020 Alex Smith
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

Import('env')

env.Object('%s/crt1.o' % (str(env['_LIBOUTDIR'])), ['crt1.S'])
env.Object('%s/crti.o' % (str(env['_LIBOUTDIR'])), ['crti.S'])
env.Object('%s/crtn.o' % (str(env['_LIBOUTDIR'])), ['crtn.S'])
env.Object('%s/crtbegin.o' % (str(env['_LIBOUTDIR'])), ['crtbegin.S'])
env.Object('%s/crtend.o' % (str(env['_LIBOUTDIR'])), ['crtend.S'])
env.Object(
    '%s/crtbeginS.o' % (str(env['_LIBOUTDIR'])), ['crtbegin.S'],
    CPPDEFINES = {'PIC': None, 'SHARED': None })
env.Object(
    '%s/crtendS.o' % (str(env['_LIBOUTDIR'])), ['crtend.S'],
    CPPDEFINES = {'PIC': None, 'SHARED': None })
