# Kiwi build system
# Copyright (C) 2009 Alex Smith
#
# Kiwi is open source software, released under the terms of the Non-Profit
# Open Software License 3.0. You should have received a copy of the
# licensing information along with the source code distribution. If you
# have not received a copy of the license, please refer to the Kiwi
# project website.
#
# Please note that if you modify this file, the license requires you to
# ADD your name to the list of contributors. This boilerplate is not the
# license itself; please refer to the copy of the license you have received
# for complete terms.

import os
import sys

Import('env', 'envmgr', 'config')

# Set IA32-specific compilation flags.
env['ASFLAGS'] += ['-m32']
env['CCFLAGS'] += ['-m32', '-fno-omit-frame-pointer', '-march=i686']
env['LDFLAGS'] += ['-b', 'elf32-i386', '-m', 'elf_i386']

# We need to link the kernel with libgcc, and force some symbols from it to be
# linked in.
env['LDFLAGS'] += [os.popen('%s -print-libgcc-file-name' % envmgr.base['CC']).read().strip()]
env['LDFLAGS'] += ['--undefined=__moddi3', '--undefined=__divdi3']

# Pull in x86 common code.
SConscript(dirs=['../common/x86'], exports=['env'])

# Add source files.
env['OBJFILES'] += [
	env.Object('arch.c'),
	env.Object('boot.S'),
	env.Object('context.c'),
	env.Object('descriptor.c'),
	env.Object('elf.c'),
	env.Object('entry.S'),
	env.Object('kdbg.c'),
	env.Object('page.c'),
	env.Object('switch.S'),
	env.Object('thread.c'),
]
