#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_sources')
from util import feature_sources

# Built-in driver.
kern_sources += feature_sources(config, [
    'arm_timer.c',
])
