#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'mod_env')

if config['ARCH'] == 'amd64':
    pci_platform = 'pc'

mod_env.Module('pci', [
    'platform/%s.c' % (pci_platform),
    'pci.c',
])
