#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'kern_sources')
from util import feature_dirs, feature_sources

kern_sources += feature_sources(config, [
    'ramfs.c',
])

SConscript(dirs = feature_dirs(config, [
    ('FS_EXT2', 'ext2'),
]))
