#
# SPDX-FileCopyrightText: (C) Alex Smith <alex@alex-smith.me.uk>
# SPDX-License-Identifier: ISC
#

Import('config', 'mod_env')
from util import feature_dirs

mod_env.Module('disk', [
    'disk.c',
    'gpt.c',
    'mbr.c',
    'partition.c',
])

SConscript(dirs = feature_dirs(config, [
    ('DEVICE_DISK_ATA', 'ata'),
    ('DEVICE_DISK_PCI_ATA', 'pci_ata'),
]))
